version: '3.8'

services:
  gitea-committer:
    build: .
    container_name: gitea-committer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./configs/config.json:/app/configs/config.json  

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: [ --auth ]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: "mongo --eval 'db.runCommand({ ping: 1 })'"
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongodb-data:
    driver: local
