version: '3.8'

services:
  gitea-committer:
    build: .
    container_name: gitea-committer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./configs/config.json:/app/configs/config.json  

