// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"gitea.vivasoftltd.com/Vivasoft/gitea-commiter-plugin/pkg/model"
)

func UsersScript(users []model.User) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_UsersScript_8e6b`,
		Function: `function __templ_UsersScript_8e6b(users){function searchUsers() {
        
        const query = document.getElementById('searchInput').value.toLowerCase();
        const resultsDiv = document.getElementById('searchResults');
        console.log(users);
        if (query.length < 1) {
            resultsDiv.innerHTML ==''
            resultsDiv.classList.add('hidden');
            return;
        }
        resultsDiv.innerHTML = '';
        const filteredUsers = users.filter(user => {
            return (user.username?.toLowerCase().includes(query) || '') ||
                   (user.full_name?.toLowerCase().includes(query) || '') ||
                   (user.email?.toLowerCase().includes(query) || '');
        });
        if (filteredUsers.length > 0) {
            resultsDiv.classList.remove('hidden');
            // Limit to the top 5 results
            filteredUsers.slice(0, 6).forEach(user => {
                const resultItem = ` + "`" + `
                    <div class="p-2 hover:bg-gray-100 cursor-pointer" data-user-id="${user.username}">
                        <div class="flex items-center gap-4">
                            <img src="${user.avatar_url}" alt="Avatar of ${user.username}" class="w-8 h-8 rounded-full">
                            <div>
                                <div class="font-semibold">${user.username}</div>
                                <div class="text-sm text-gray-500">${user.email}</div>
                            </div>
                        </div>
                    </div>
                ` + "`" + `;
                resultsDiv.innerHTML += resultItem;
            });

            document.querySelectorAll('[data-user-id]').forEach((el) => {
                el.addEventListener('click', () => {
                    window.location.href = ` + "`" + `/users/${el.getAttribute('data-user-id')}` + "`" + `;
                });
            });
        } else {
            
            resultsDiv.innerHTML = 'No matching results';
        }
    }
    window.onload = function () {
        
        document.getElementById('searchInput').addEventListener('input', searchUsers);
    };

}`,
		Call:       templ.SafeScript(`__templ_UsersScript_8e6b`, users),
		CallInline: templ.SafeScriptInline(`__templ_UsersScript_8e6b`, users),
	}
}

func Users(users []model.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UsersScript(users).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto py-10\"><h1 class=\"text-2xl font-bold text-center mb-8\">Search Users</h1><div class=\"relative px-10\"><input type=\"text\" id=\"searchInput\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg\" placeholder=\"Search users by username, full name, or email...\"><!-- Results Container --><div id=\"searchResults\" class=\"z-10 mx-auto w-full bg-white border border-gray-300 rounded-lg shadow-lg hidden\"></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
